/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0d131f",
        "secondary-fixed": "#ffe088",
        outline: "#909096",
        "error-container": "#93000a",
        "inverse-primary": "#595e6f",
        "secondary-container": "#af8d11",
        "on-tertiary-container": "#7b7976",
        tertiary: "#c8c6c2",
        "primary-fixed-dim": "#c1c6da",
        "inverse-on-surface": "#2a303d",
        "on-primary": "#2b3040",
        "on-secondary-container": "#342800",
        "on-primary-fixed": "#161b2a",
        error: "#ffb4ab",
        secondary: "#e9c349",
        "surface-variant": "#2f3542",
        "surface-bright": "#333946",
        "surface-container": "#1a202c",
        "surface-container-highest": "#2f3542",
        "tertiary-fixed-dim": "#c8c6c2",
        "on-secondary-fixed": "#241a00",
        "on-tertiary": "#31302e",
        "on-secondary": "#3c2f00",
        "surface-tint": "#c1c6da",
        "on-secondary-fixed-variant": "#574500",
        "primary-container": "#050a18",
        "primary-fixed": "#dde2f6",
        background: "#0d131f",
        "secondary-fixed-dim": "#e9c349",
        "on-primary-fixed-variant": "#414657",
        "surface-container-lowest": "#080e1a",
        "outline-variant": "#45464c",
        "surface-container-high": "#242a36",
        "on-tertiary-fixed": "#1c1c19",
        "on-surface": "#dde2f3",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#474744",
        "on-primary-container": "#74798b",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#e5e2de",
        "on-surface-variant": "#c6c6cc",
        "surface-container-low": "#161c27",
        "on-background": "#dde2f3",
        primary: "#c1c6da",
        surface: "#0d131f",
        "tertiary-container": "#0b0b09",
        "inverse-surface": "#dde2f3",
      },
      fontFamily: {
        "headline-lg-mobile": ["Bodoni Moda"],
        "label-caps": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "headline-md": ["Bodoni Moda"],
        "headline-display": ["Bodoni Moda"],
        "headline-lg": ["Bodoni Moda"],
        "body-md": ["DM Sans"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "0em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-display": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "0em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.02em", fontWeight: "400" }],
      },
      spacing: {
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        base: "8px",
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}
